name: Trigger auto deployment for app001

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ gh-pages ]
    paths:
    - '**'
    - '.github/workflows/app001-AutoDeployTrigger-59e0d46f-9a00-4fa3-81c5-345368a0fb84.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APP001_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APP001_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APP001_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.APP001_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APP001_REGISTRY_PASSWORD }}
          containerAppName: app001
          resourceGroup: RG-day4-01
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


